### Get list of users saved in database <UNPROTECTED route>
GET http://localhost:8080/api/v1/users/list

### Creates a new user in db and returns access and refresh token <UNPROTECTED route>
POST http://localhost:8080/api/v1/users/create
Content-Type: application/json

{
    "email": "String",
    "password": "String(4,15)"
}

### Logins the user and returns access and refresh token <UNPROTECTED route>
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
    "email": "String",
    "password": "String"
}

### Logs out the current user and delete the access and refresh token <PROTECTED route>
DELETE http://localhost:8080/api/v1/users/logout
Authorization: Bearer <TOKEN>

### Creates a book entry in the database
POST http://localhost:8080/api/v1/books/create
Content-Type: application/json

{
    "author": "String",
    "title": "String",
    "genre": "String",
    "publisher": "String",
    "price": Number,
    "availability": null/Date
}

### Get the particular book details 
GET http://localhost:8080/api/v1/books/id/<book_id>

### Get list of books with different conditions, sorting, pagination
GET http://localhost:8080/api/v1/books/list?title=&author=&publisher=&genre=&s_price=&e_price=&sort_field=&sort_type=&offset=0&limit=10

### Add a book in user cart <PROTECTED route>
POST http://localhost:8080/api/v1/cart/add/<user_id>
Authorization: Bearer <TOKEN>
Content-Type: application/json

{
    "book_id": Number,
    "count": Number
}

### Get list of books added in the cart of user <PROTECTED route>
GET http://localhost:8080/api/v1/cart/list/<user_id>
Authorization: Bearer <TOKEN>

### Delete a book from user cart <PROTECTED route>
DELETE  http://localhost:8080/api/v1/cart/delete/<user_id>/<book_id>
Authorization: Bearer  <TOKEN>

### Create an order history for a user <PROTECTED route>
POST http://localhost:8080/api/v1/order/create/<user_id>
Authorization: Bearer <TOKEN>

### Get list of order history for any user <PROTECTED route>
GET http://localhost:8080/api/v1/order/history/<user_id>?book_id=&s_count=&e_count=&s_price=&e_price=&limit=10&offset=0
Authorization: Bearer <TOKEN>