GET http://localhost:8080/api/v1/users/list

###
POST http://localhost:8080/api/v1/users/create
Content-Type: application/json

{
    "email": "def@gam.com",
    "password": "Acsdf@1"
}

### login
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
    "email": "def@gam.com",
    "password": "Acsdf@2"
}

### logout
DELETE http://localhost:8080/api/v1/users/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlZkBnYW0uY29tIiwidXNlcl9pZCI6MiwiaWF0IjoxNjkzOTgyNDQ1LCJleHAiOjE2OTQwNjg4NDV9.NS5BCodGHbYJ3qHZqDOS03StiLLHQMhtiReY4lJY5a0

### 
POST http://localhost:8080/api/v1/books/create
Content-Type: application/json

{
    "author": "Agatha Christie",
    "title": "Murder on the Orient Express",
    "genre": "Mystery",
    "publisher": "William Collins",
    "price": 9.95,
    "availability": null
}

###
GET http://localhost:8080/api/v1/books/id/3

###
GET http://localhost:8080/api/v1/books/list?title=&author=&publisher=&genre=&s_price=&e_price=&sort_field=&sort_type=&offset=0&limit=10
